-- Production seed intentionally contains no businesses, prices, ratings, queue activity or advertising.
-- Import verified GTA data through the protected ingestion workflow after reviewing provider terms.
