-- Founder analytics hardening.
--
-- 1. analytics_events was created with a bigint primary key but no default/identity,
--    so server-side telemetry inserts could be accepted by the Edge Function while
--    silently failing at the database insert.
-- 2. internal_service_config stores server-only integration values. RLS is enabled
--    with no browser policies; only the service role may read it.

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'analytics_events'
      and column_name = 'id'
      and is_identity = 'NO'
      and column_default is null
  ) then
    alter table public.analytics_events
      alter column id add generated by default as identity;
  end if;
end
$$;

create table if not exists public.internal_service_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.internal_service_config enable row level security;
revoke all on table public.internal_service_config from anon, authenticated;
grant select on table public.internal_service_config to service_role;

comment on table public.internal_service_config is
  'Server-only integration configuration. No anon/authenticated browser access.';
